### ISSUE TITLE
Color scheme switcher is confusing

### ISSUE THREAD

**Issue by Exalm** [flxzt/rnote#10]
There are grey, white and dark dots. the first two don't appear to be any different, the last one makes the UI dark but not the canvas.

The tooltips say default/prefer light/prefer dark, probably referencing the new color scheme thing, but that doesn't seem to work as expected either:

* when system prefers light/dark, all 3 modes in the app behave the same
* when system doesn't prefer anything, white and grey behave the same

So I'm honestly not sure what the intention was with these.

**Comment by flxzt** [comment]
the light / dark buttons should overwrite the system preference now. The first grey button (default) is if you don't have any preference, which means the app color scheme should change with the system preference in the future (can't test it myself, im on Gnome 41 / Fedora 35 beta)

**Comment by Exalm** [comment]
Thanks! It can be tested with GtkInspector if you have new enough libadwaita - see https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/Dark-Style-Preference#libadwaita

**Comment by flxzt** [comment]
Ah very useful, thanks! Regarding canvas background color, I dont consider it part of the theme. I didn't implement the setting to set the background to a different color or pattern yet but its planned

**Comment by Exalm** [comment]
A part of the theme - whatever, but there isn't much of a point in having a dark window if  it's only tiny header bar and 95% of the window doesn't change, is there? :)

**Comment by flxzt** [comment]
I disagree :D Think about it, lets say you take notes with a black or dark blue pen during the day, it gets dark and you or [a extension](https://extensions.gnome.org/extension/2236/night-theme-switcher/) changes the color scheme to a dark preference. It would be very annoying and imho app breaking when you have to change your entire application to light again because you can't read the text you wrote earlier. Maybe it could switch automatically when the sheet is still empty, but even then I think its better to have it as a separate color option. And with background patterns (eg. graph paper) it would get messy really fast so I want to avoid that

**Comment by Exalm** [comment]
Check how iOS notes app handles it. Obviously black text on black bg is a no-go, that's not what I'm suggesting. :)
