### ISSUE TITLE
Option to open Workspace in file manager

### ISSUE THREAD

**Issue by mahdihasan2006** [flxzt/rnote#1053]
**Problem**

The Workspace file browser doesn't have much features like searching, renaming etc.

**Suggested solution**

Add an option to open the Workspace in the default file manager. I think this option is useful even if you add searching, renaming etc. features in the app.

**Optional**

You may add the option in the red marked location or wherever you find good.

**Additional context**

![image](https://github.com/flxzt/rnote/assets/121625152/b3ac22f2-d115-4645-86e9-8b3f3ce75bd4)

**Comment by silvasch** [comment]
Do you want to rename the workspace or a file/folder in the workspace? Because there is an option for both. You can rename files and folders from the the three dots menu (or open them in the default app):
![image](https://github.com/flxzt/rnote/assets/128063006/4f59ef46-2674-4ce2-a746-a3deac983869)

And you can edit workspaces by pressing on the pen in the bottom right:
![image](https://github.com/flxzt/rnote/assets/128063006/db29517b-bc34-418e-a890-0347e57e8cc0)

**Comment by flxzt** [comment]
The appropriate place to add the ability to open the workspace location with the default file manager would be an additional action in the folder-actions menu (the one that can be opened with the folder-three-dots button)

**Comment by mahdihasan2006** [comment]
Sounds good.

But I have a suggestion. Because there will be just two actions, why not directly add two icons for two actions reducing clicks. Decision is up to you.

**Comment by flxzt** [comment]
I'd prefer it to be in the menu, that's the intended place for such additions

**Comment by mahdihasan2006** [comment]
Okay, no problem.
