### ISSUE TITLE
Problem at the moment of Export the archive,

### ISSUE THREAD

**Issue by Fsayajin** [flxzt/rnote#1073]
When I save an archive, it exports as a '.archive' file, but it can't be opened with any program, including Rnote. This issue occurs most of the time, although occasionally it works. Additionally, today I encountered problems when saving the PDF archive. I'm working with Rnote Version 0.10.0 on Windows 11.

**Comment by Doublonmousse** [comment]
Can you provide screenshots of the process, I'm not sure I understand what you mean.

**Comment by Fsayajin** [comment]
This is what I mean: I discovered that the problem arises when I change the name of the file during download. If I don't change the name, the file is saved as '.Rnote', which is what is expected (Documento Nuevo). However, if I change the name to something else, such as "Documento Nuevo 2", then it can't be opened, and it is saved as '.archive'.
![Captura de pantalla 2024-04-10 101516](https://github.com/flxzt/rnote/assets/143981629/659ee918-a707-4e7e-9fc8-014fda014b9b)
![Captura de pantalla 2024-04-10 101929](https://github.com/flxzt/rnote/assets/143981629/b5c7f6c8-6723-46a7-9967-8f762f423101)
The second picture shows the different ways I tried to download the file. However, the same issue occurred in all cases. (I apologize for translating the button names to English in that manner, but I have the program set to Spanish.)

**Comment by silvasch** [comment]
I'm not sure, but I think you have to save it with a `.rnote` file ending. So the new file name should be `Documento nuevo 2.rnote`

**Comment by Doublonmousse** [comment]
Oh right I see what you did. The file is selected, including the `.rnote` file ending
![image](https://github.com/flxzt/rnote/assets/115779707/c36f2049-7273-4972-96ef-1cf27fab0507)

So that changing the name without removing the selection (or only modifying the first part) will end up with a file that has no extension upon saving

![image](https://github.com/flxzt/rnote/assets/115779707/2f6b6df0-192f-4f30-88f3-62b921e64263)

**Comment by Doublonmousse** [comment]
Found the reason, the filter is not working in the file chooser because it seems right now that you cannot set a default filter without giving a list of filters first and choosing from this list 

From the `gtk-rs` documentation :

If it is not (`filters` is none), the dialog may choose to not make it available.  (for the default filter)
