### ISSUE TITLE
mime-icon not shown with nautilus file manager

### ISSUE THREAD

**Issue by Nokse22** [flxzt/rnote#1166]
**Describe the bug**  
The mime type is correctly installed, because I can get it with `xdg-mime query filetype file.rnote` and it returns `application/rnote`, but the icon is the default one.

**To Reproduce**  
1. Install the app
2. Save a file
3. No icon :(

**Expected behavior**  
The custom rnote mime icon should be visible

**Desktop (please complete the following information):**  
 - OS: Fedora 40
 - App Version: 0.11.0
 - Installation Source: Flatpak
 - Desktop Environment: Gnome 46
 - Display Server: Wayland
 
**Additional context**  
Other flatpak apps can install mime type icons.
Tried reinstalling the app multiple times.

**Comment by flxzt** [comment]
I was under the impression that this is because of nautilus behavior - if the icon for the application is not present in the libadwaita theme, instead of falling back to `hicolor/scalable/mimetypes/application-rnote.svg` (where it actually is installed), nautilus only display the generic document icon you probably are seeing.

Other file managers like thunar handle this differently, and do work.

Which applications handle this differently? I'd be interested if there something that can be done on our side. But otherwise, this is kind of an issue with nautilus and I remember there is an open issue about this somewhere on their bug-tracker as well.

**Comment by Nokse22** [comment]
I have made an app recently that installs mime icons with nautilus correctly [like this](https://github.com/Nokse22/Exhibit/blob/a2c0f648b0ebf842b3d3d270df94bae1e63aca0d/data/meson.build#L42-L48), I have seen that you do it in a similar way, so I don't know what could be causing it.

Also Cambalache installs mime icons https://gitlab.gnome.org/jpu/cambalache

**Comment by flxzt** [comment]
turns out changing `<icon>` to <generic-icon>` makes nautilus use it, like in your app `Exhibit`.

fixed with commit 2e0d148221879d2c98f80245fe9ccc4481f7bced

**Comment by Nokse22** [comment]
Great! I didn't notice it.
