### ISSUE TITLE
Blurry PDF 

### ISSUE THREAD

**Issue by piotrnajda3000** [flxzt/rnote#125]
On 100% canvas zoom, I import a PDF at the default of 65% (set in settings) as a vector. 

The text is blurry as shown here: 

![image](https://user-images.githubusercontent.com/58721991/156895446-6132db49-3617-46fe-96db-0c11ac9d3366.png)

At closer zooms, the text becomes sharper and sharper, however the PDF simply becomes uncomfortably big. 

Ubuntu 20.04 LTS, Nvidia proprietary drivers (nvidia-driver-470), installed w/ Flathub, latest version. 

Thank you for your work!

**Comment by piotrnajda3000** [comment]
It appears that I have the same blur using both Drawboard and Xournal++ for annotating PDF...

**Comment by flxzt** [comment]
Maybe the cause is your display scaling factor in Gnome settings? If set to anything else than 100% usually results in some blurriness in various apps

**Comment by piotrnajda3000** [comment]
> Maybe the cause is your display scaling factor in Gnome settings? If set to anything else than 100% usually results in some blurriness in various apps

Unfortunately, it's set to 100%.

**Comment by flxzt** [comment]
I am not sure if this is a rnote specific issue. Since you have the issue in other apps to, this is probably just the [Anti-Aliasing](https://de.wikipedia.org/wiki/Antialiasing_(Computergrafik)) of the 2d graphics libraries used to render the pdf pages. I don't think there is much that can be done here..
