### ISSUE TITLE
Stylus - Second Button Support

### ISSUE THREAD

**Issue by Mr-EmPee** [flxzt/rnote#128]
Heya, I've a common stylus with two buttons.

I think that providing a way to temporary use the selection
with the second stylus button would be a great addition.

**P.S.** 
I've read #18, and I think that this should be treated as a different issue.

**Comment by flxzt** [comment]
I tried to implement a quick hardcoded solution to map the second button like the temporary eraser, but apparently my the second button is not supported on my pen (`tool_type()` always returns `Pen` with the second button. The first button returns `Eraser`). GTK4 stylus input is kind of buggy in my experience, but maybe someone could take a look at it by running the dev build. I added some logging so that the output displays the current button and tell if it is different for them so that I know how to implement it.

**Comment by flxzt** [comment]
An initial implementation landed in v0.4.0. It maps the second button to the selector by default, but is reconfigurable in the settings.

**Comment by Mr-EmPee** [comment]
Works like a charm! Great Job
