### ISSUE TITLE
Unable to save document

### ISSUE THREAD

**Issue by homailali** [flxzt/rnote#1303]
**Bug**
I am not able to save a document error that appears in a little snack bar at bottom is **saving document failed**

**Reproduce**
To reproduce create a new document write something and then save it

**Console output**
Caused by:
    Permission denied (os error 13)
2024-11-21T01:32:59.298107Z ERROR rnote::overlays: Saving document failed

**Desktop**
 - OS:  Ubuntu 24.04.1 Lts 64 bit  
 - App Version: 0.10.2
 - Installation Source: Snap
 - Desktop Environment: Gnome 46

**Additional context**
The document is indeed getting saved in the home directory (e.g /home/user/) but it is not getting saved in the location /home/user/Disks/D where D is a sata hard drive mounted at this location

**Comment by Doublonmousse** [comment]
Can you check on the latest version, 0.11 ?

**Comment by Kneemund** [comment]
Please use the issue template and post the logs. 

It sounds like a permission error due to the sandbox restrictions. It could also be a packaging error. 

Either way, please be aware that the snap is unofficial, unsupported and seemingly out of date. You can report bugs related to the packaging [here](https://github.com/soumyaDghosh/rnote-snap).

**Comment by homailali** [comment]
> Please use the issue template and post the logs.
> 
> It sounds like a permission error due to the sandbox restrictions. It could also be a packaging error.
> 
> Either way, please be aware that the snap is unofficial, unsupported and seemingly out of date. You can report bugs related to the packaging [here](https://github.com/soumyaDghosh/rnote-snap).

i have updated my issue.

**Comment by Kneemund** [comment]
Thanks. Yeah, it's a permission error because apparmor/snap doesn't allow rnote to access that path - probably because you symlinked it from somewhere else (accessing the home directory *should* work). I have no idea about apparmor/snap, you might be able to configure it.

But considering that using the flatpak version works for you, that's probably the best solution regardless :P
