### ISSUE TITLE
Enchancement: Allow for the pen to interact with the UI

### ISSUE THREAD

**Issue by giannissc** [flxzt/rnote#21]
With the current implementation UI button can be pressed using the pen input. At least that is the situation under Wayland i haven´t actually checked what is happening with X11 just yet but I will update this bug when I do. From my understanding the different between X11 and Wayland is that with X11 the mouse pointer and the pen pointer are one and the same. However, under Wayland these two have separate coordinates. That might just be the source of the bug

**Comment by flxzt** [comment]
Are you not able to click anything at all with the stylus or does the focus sometimes 'get stuck' in the canvas? Because I am experiencing that on Wayland, but not on X11. What usually helped is to tap anywhere outside the application ( e.g. the top bar of GNOME). Not that that is a recommended fix, but it would help me identify that its the same behaviour I am having too. Also this might be the same issue as #9.

**Comment by giannissc** [comment]
So it is a weird behaviour.. I am indeed able to change a tool but when I try to interact with any part of the application (headerbar, canvas, tools, etc. ) the only thing that happens is the the app moves where the pen does. See below for video below. As you can also see from the video the behaviour is very erratic. First time I tried selecting another tool suing the pen it didn't work but the second time it it. Hope that helps a bit. As to issue #9 is would probably close that as this issues is more general

https://user-images.githubusercontent.com/20277283/143582248-ed4503a3-122a-4c05-aa64-8969f5fb1f6a.mp4

o

**Comment by flxzt** [comment]
Does this glitch still happen? Looks pretty bad tbh..

**Comment by giannissc** [comment]
I can confirm that the issue has been solved. I will reopen if the issue reappears
