### ISSUE TITLE
Shape sub-options

### ISSUE THREAD

**Issue by defini-tiv** [flxzt/rnote#232]
**Is your feature request related to a problem? Please describe.**
Shape builders list has multiple entries for same shapes.
It is bigger than it needs to be and will get bigger with every additional option.

**Describe the solution you'd like**
Having only one options for every shape type (Line, Rectangle, Ellipse, Curve) and move other Options to a Shape sub-Options menu.
It could be where the constraints options are currently.  I think it fits there better  because it would be in closer relation to the shape you want to draw.

**Describe alternatives you've considered**
Maybe a fold-out sub menu for every shape builder in the list?

**Comment by flxzt** [comment]
Fold-out rows seem like a good option to categorize the different shape builders when the list grows in the future.

**Comment by Kneemund** [comment]
What do you think about something like this? The margins are very large and you can seemingly only adjust the top and bottom margin of the grid, and I'm not entirely sure about how this could be hooked up internally. You have to click next to the grid in order to actually select the shape. This seems to be one of the few options that work; I couldn't get collapsible (and selectable) rows to work *at all*.

[Bildschirmaufzeichnung vom 2022-12-24, 15-52-19.webm](https://user-images.githubusercontent.com/49598842/209441438-1ac0679b-93d2-4e19-88c3-6152d07ebfaa.webm)

**Comment by flxzt** [comment]
That could be an alternative, though I don't like that "You have to click next to the grid in order to actually select the shape". And we'd need to think about when groups have more than three shapes (e.g. different splines ), that would grow the list horizontally. Though as long as the shape group name stays short it shouldn't be too much of a problem.

> I couldn't get collapsible (and selectable) rows to work at all  

Ah, thats unfortunate. That would have been the most elegant solution in my opinion.  

Regarding styling and margins, that can be tweaked by css with negative margin values, the same way the margins for the big icons in the sidebar are reduced.

The other solution would be to do a icon grid, "IconPicker" could be reused for that

**Comment by Kneemund** [comment]
There are definitely flaws to this, yeah. Maybe you could move the shape selection using code when an element in the grid is clicked?

> Ah, thats unfortunate. That would have been the most elegant solution in my opinion.

It might be possible, but I just didn't manage to get it working. Every combination of UI elements I've tried had some flaws (visually and functionally). I'm not too familiar with GTK/libadwaita though.

> The other solution would be to do a icon grid, "IconPicker" could be reused for that

How would you arrange/group the icons? I'm not sure if the icons are sufficiently descriptive at a glance. I'd personally prefer having some kind of name or description. 

Maybe you could modify the icon picker to behave similarly to the emoji picker, i.e. have a heading with the name of the shape group, and the icons of the shapes below it. But that probably wouldn't look very elegant for e.g. groups with only 1 element.

**Comment by flxzt** [comment]
#455
