### ISSUE TITLE
Custom install path gives error

### ISSUE THREAD

**Issue by TornaxO7** [flxzt/rnote#273]
**Describe the bug**
I'm getting an error if I'm trying to run `rnote`:
```rust
(rnote:23052): GLib-GIO-ERROR **: 19:32:15.606: Settings schema 'com.github.flxzt.rnote' is not installed
[1]    23052 trace trap  ~/.local/bin/rnote/bin/rnote
```

**To Reproduce**
Execute the following:
```bash
# prepare the installation place
export PATH=$PATH:~/.local/bin/rnote/bin/rnote
mkdir -p ~/.local/bin/rnote

# clone the repo anywhere
git clone https://github.com/flxzt/rnote
cd rnote
git submodule update --init --recursive
cd rnote

# it's install time!
meson setup --prefix=/home/$USER/.local/bin/rnote build
meson install -C build

# execute it!
~/.local/bin/rnote/bin/rnote
```

**Expected behavior**
That it'd work

** Console Output **
```
(rnote:31886): GLib-GIO-ERROR **: 19:37:23.517: Settings schema 'com.github.flxzt.rnote' is not installed
[1]    31886 trace trap  ~/.local/bin/rnote/bin/rnote
```

**Screenshots**
Not needed.

**Desktop (please complete the following information):**
 - OS: `Artix`
 - Version: `5.19.12-artix1-1`
 - Installation source: Repo
 - Desktop Environment: `leftwm`

**Additional context**
Grüße von ~~Kerlsruhe~~Karlsruhe :)

**Comment by flxzt** [comment]
The issue is that only paths in `XDG_DATA_DIRS` is searched for available settings. I could not find a way to add add a custom search path within the application, so I see two ways to make it work:
- Either install the application once to `/usr` to make the settings available. You would only need to reinstall when adding / modifying setting keys.
- Add the custom path to `XDG_DATA_DIRS` .

You could also start using the development flatpak manifest, which isolates the dev build nicely from the host environment and works completely without sudo.

Grüsse zurück aus dem Ländle. :)

**Comment by TornaxO7** [comment]
> Add the custom path to XDG_DATA_DIRS

Hm... setting `XDG_DATA_DIRS=~/.local/bin/rnote` didn't work :thinking: well, I'll try the flatpak variant then.

**Comment by flxzt** [comment]
I think it has to be the equivalent of `/usr/share`, the parent of the `glib-2.0` folder to get picked up
