### ISSUE TITLE
[Feature Request] A toogle button to use stylus as a pointer

### ISSUE THREAD

**Issue by ritamsaha00** [flxzt/rnote#313]
**Please submit only one feature request in one issue!**

If it is UX / UI related, don't post how a single aspect of the UI should be changed, but rather in which use case you felt the UI is lacking or should be improved.

I think the request I am making is useful to all use cases of handwritten note-taking (sorry if that doesn't make sense to you.) With this, taking handwritten notes will be more seamless.

**Is your feature request related to a problem? Please describe.**
When I am using my stylus, I can't scroll with touch. I have to move my stylus out of my screens range to use finger touch as finger touch and stylus input doesn't work together, and you can't use the stylus as a pointer

**Describe the solution you'd like**
A new feature that allows users to toggle stylus input as a pointer.

**Describe alternatives you've considered**
Allow both stylus input for drawing/writing and touch input for scrolling at the same time

**Additional context**
![image](https://user-images.githubusercontent.com/69363775/197488241-3ab12998-214d-4f78-966b-289b66e9dfbe.png)

This space on the left corner is pretty much useless. You can add a toggle button here.

**Comment by Heiseneberg-maybe** [comment]
I think  this is actually a bug, because I am able to move the canvas with the touch input while the pen is hovering.
[moving canvas with touch and writing with stylus.webm](https://user-images.githubusercontent.com/104737846/197985042-425f68f6-c7f3-41ab-bd9e-4ae3675a8d00.webm)
Like shown in this video, let me know if I misunderstood you

**Comment by ritamsaha00** [comment]
I think you might be right. I will check if I am doing something wrong. And if it's a bug, I will add more context.

**Comment by ritamsaha00** [comment]
@Heiseneberg-maybe I don't know if it's clear from the video, but this is what happened when I tried to scroll.
[Screencast from 28-10-22 08:46:10 AM IST.webm](https://user-images.githubusercontent.com/69363775/198494607-932c9eba-8983-4f3d-a3d5-59b0e2581e57.webm)

When it's taking stylus input the page wouldn't scroll, but it will when I remove the stylus from proximity.

**Comment by Heiseneberg-maybe** [comment]
Alright, what happens is that the right side of the screen is blocked from receiving inputs starting from a bit left (there is a padding) of the point in which the "Regular cursor" is present in the canvas. (The "Regular cursor" is the cursor that is present when hovering the screen with the stylus).
This is done in order to prevent accidental touch inputs from the possible resting hand that is present on the screen.

In conclusion you can actually move the canvas with the touch input when the "Regular cursor" is present, but you need to use the left side of the screen. 

What I think you do is trying to move the canvas using one of the fingers of the hand with which you're holding the stylus, thus being in the right side which is blocked. 
You could use the other hand to move the canvas (from the left of the position of the "Regular cursor")

This assuming you're right-handed, because there is a problem: #329

Are you left-handed? Because that too would explain the fact that you encountered this issue. 

Anyway, I noticed that the feature you actually want is already present in the Tools section, it's the second one. 
You can with it offset the camera by dragging the canvas.

**Comment by flxzt** [comment]
I too think this is a bug. I would close this in favor of #329, because the `tools` page already has a drag tool implemented where you can use your stylus to move around. ( Unless I misunderstood your request )
