### ISSUE TITLE
Enable one-click building in Builder

### ISSUE THREAD

**Issue by bertob** [flxzt/rnote#359]
To make contributions easier it'd be great if this app could be built in GNOME Builder. This requires a `json` flatpak manifest somewhere in the repo. There does seem to be a manifest in this case, but it's `yaml`, so it doesn't work. Simply converting the manifest should work.

**Comment by flxzt** [comment]
You can always build natively with meson. But you are right, gnome builder currently [does not support yaml](https://gitlab.gnome.org/GNOME/gnome-builder/-/issues/520) . 

I want to keep the manifest in yaml format, because it is a lot more pleasant to write and supports comments, but it is easy to convert to json with `yq` by running:
```
yq -o=json com.github.flxzt.rnote.Devel.yaml > com.github.flxzt.rnote.Devel.json
```

I'll update the json whenever I modify the yaml file.
