### ISSUE TITLE
Only show scrollbars optionally?

### ISSUE THREAD

**Issue by bertob** [flxzt/rnote#373]
For an infinite canvas style app it's a bit weird/distracting to have visible scrollbars, since you generally navigate with a touchpad and/or shift/ctrl+scroll. I wonder if they're needed at all, or if they could at least be opt-in somehow.

**Comment by Heiseneberg-maybe** [comment]
You can hide them activating the "Permanently hidden scrollbars" option in the settings

**Comment by bertob** [comment]
Ah, good to know! I'd just flip the default state on that option then :)

**Comment by bertob** [comment]
By the way, is there a reason why the horizontal scrollbar is at the top rather than the bottom? It's a bit odd, since nothing else does it that way.

**Comment by maymage** [comment]
> For an infinite canvas style app it's a bit weird/distracting to have visible scrollbars, since you generally navigate with a touchpad and/or shift/ctrl+scroll. I wonder if they're needed at all, or if they could at least be opt-in somehow.

Actually the lack of scroll bars can be an issue. Suppose, you only work with a pen and the window is so small, that the
gray dragable areas to the left and right of the sheet are non visible. How'd you scroll down then without dragging and without a scroll bar?

**Comment by flxzt** [comment]
@bertob I try to keep the corner where the writing arm and palm rests clear from interactive UI, because some reported that the palm /touch rejection can be unreliable. Some users complained that the scrollbars would activate when they were at the bottom left / right, so I moved them to the other corners

**Comment by bertob** [comment]
Ah, interesting. If you have a pen you would probably not also have the scrollbars though, right? Are there tablets that support pen but not touch to pan/zoom the canvas?

**Comment by flxzt** [comment]
I assume most "external" graphic tablets don't have that or an emulated middle mouse button drag is awkward to use. I know that there are some users that rely on "surfaces" / widgets to scroll, because there was a feature request from a tablet user some time ago that wanted to have a scroll drag gesture connected on the background ( which is visible in the width restricted layout modes )

**Comment by flxzt** [comment]
I'll change the default, and the setting should then also be changed to be not negated.
