### ISSUE TITLE
optimize CI workflow 

### ISSUE THREAD

**Issue by Kneemund** [flxzt/rnote#393]
The CI workflow can be optimized a bit. 

### Caching cargo build files and downloads.

![grafik](https://user-images.githubusercontent.com/49598842/206018009-df0f00c6-ab29-4724-b203-ba2d2dd28e5f.png)
![grafik](https://user-images.githubusercontent.com/49598842/206018112-8ae03ccf-b79a-474a-8153-9adc5b164ba4.png)

The bottom run is one without any caching, but also includes building the cache (took 2m 11s in this case).
The top run has an [exact cache hit](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#cache-hits-and-misses) and is about twice as fast.

One cache is about 1GB ATM; GitHub allows for 5GB per cache and 10GB in total (older caches are automatically deleted if that limit is exceeded AFAIK). This could be fine-tuned if it ever becomes too big (e.g. only cache the build artifacts - downloading the dependencies is much quicker).

### Caching fedora packages.

The workflow could use a custom docker image hosted on docker hub that already contains all the needed dependencies, but maintaining that would be more difficult/fragmented. I'm not sure how you would otherwise (safely) cache `dnf` packages though.
This would shave off another 2.5 minutes. The `Dockerfile` would look something like this:

```dockerfile
FROM fedora:37

RUN dnf upgrade --refresh -y
RUN dnf install -y meson gcc gcc-c++ clang make automake cmake kernel-devel gtk4-devel libadwaita-devel poppler-glib-devel poppler-data alsa-lib-devel
```

Using e.g. `ubuntu-latest` instead of a container would also be faster, but not as fast as a custom image (and currently impossible due to ubuntu's GTK4 package being too old).

---

Not a PR yet because this needs to be discussed first, especially if the docker hub solution sounds good to you.

**Comment by Kneemund** [comment]
Using a prebuilt image of the `Dockerfile` above, you get down to about 3m 2s (best possible circumstances). Downloading and verifying non-official images from DockerHub takes longer than I expected. I'm not sure if that's really worth the effort of maintaining an image.

**Comment by flxzt** [comment]
Thanks for looking into it, there is definitely a lot that can be improved here. I am not very familiar with containers and CI, thats definitely an area I need to look into more. But because of that, I also would like to keep things as simple as possible.

I can't really add much here, you'd need to tell if its worth it. We could first start without the custom image, as that already brings a big improvement. We can always follow up with it later.

Related: We should probably also discuss what should actually be run as CI, the existing workflow is very lacking. I am thinking about switching to `meson` in the CI to get rid of the `config.rs` annoyance and to have more extensive tests around desktop, appdata, resources, ... files. I have to look into how to best integrate `cargo check` and possibly `cargo clippy`.

I believe some other gtk apps (mainly on gitlab) are using CI with flatpaks ( so maybe there are some docker images already available ), that could be another route. I believe are also ways to cache certain parts of flatpak builds similar to how the vscode extension does it. The benefit of that would also be that it would be the same environment to how rnote is primarily distributed.

**Comment by Kneemund** [comment]
I experimented a bit with CD/flatpak-builder, but I can't get the caching to work properly. It does work for poppler, but meson or flatpak-builder always create a new directory for building rnote on each subsequent build, ignoring the cache:

![grafik](https://user-images.githubusercontent.com/49598842/206916427-3ceb1846-194b-4681-b148-ae725e1aaa70.png)

I have no idea how the VS Code extension does it, but that could give us a bit more insight.
Without (fully working) caching, this takes about 2x as long as the current (also uncached) CI.

**Comment by flxzt** [comment]
Did you tell cargo the path to the packages with CARGO_HOME (see [here](https://github.com/flxzt/rnote/blob/a1a7b745712296f1bfdcc11a2a7395f636edd6d7/meson.build#L115) ?)

**Comment by Kneemund** [comment]
I've just tried that (using an absolute path); it didn't work. The VS Code extension builds the dependencies using multiple steps. Or more specifically, it builds rnote separately from poppler, by first executing meson configure and then using ninja for building it.

This is the command that the [flatpak GitHub Action](https://github.com/marketplace/actions/flatpak-builder) executes:
```sh
/usr/bin/xvfb-run --auto-servernum flatpak-builder --repo=repo --disable-rofiles-fuse --install-deps-from=flathub --force-clean --default-branch=master --arch=x86_64 --ccache flatpak_app build-aux/com.github.flxzt.rnote.Devel.yaml
```

I'm not seeing any configuration options that could help here. We basically have either have to write our own workflow from scratch, or get the caching to work by modifying the build process/manifest/whatever.
