### ISSUE TITLE
Hamburger Menu looks weird

### ISSUE THREAD

**Issue by Joshix-1** [flxzt/rnote#465]
**Describe the bug**
The hamburger menu looks weird.

**To Reproduce**
1. See the hamburger menu

**Expected behavior**
It should be three vertical lines

**Screenshots**
![image](https://user-images.githubusercontent.com/57299889/214151298-90c62530-b06e-426d-97a8-9b669f47c916.png)
![image](https://user-images.githubusercontent.com/57299889/214151408-902a36c2-cdfe-4602-b0d5-8f4a562cd9cf.png)

**Desktop (please complete the following information):**
 - OS: Arch
 - Version: rnote-0.5.12-1
 - Installation source: Archlinux Community Repo
 - Desktop Environment: XFCE

**Additional context**
 It took me half an hour to find export to pdf :(

**Comment by flxzt** [comment]
Can you please use the bug report template? It is there for a reason.

Also I think your menu icon is either broken or not adapting to the light theme. Likely not something that can be fixed by Rnote. You'd need to fix that on your system / distribution.


This is how it looks by default on fedora:  

![Bildschirmfoto vom 2023-01-23 21-58-26](https://user-images.githubusercontent.com/19841886/214148798-94cc36a7-623c-48a9-86cb-85ee91e66f2b.png)

and on ubuntu:

![Bildschirmfoto vom 2023-01-23 22-03-06](https://user-images.githubusercontent.com/19841886/214149467-edaa220c-416a-4d07-b225-4f4a35ae919c.png)

**Comment by Joshix-1** [comment]
The problem is with the icon pack of my sytem. Sorry for bothering. I just got annoyed
