### ISSUE TITLE
Use standard icons for headerbar buttons

### ISSUE THREAD

**Issue by bertob** [flxzt/rnote#483]
Is there a particular reason the app isn't using the default `sidebar-show-right-symbolic`/`sidebar-show-leftsymbolic` for the sidebar toggle, and `tab-new` for new tab? If not I'd switch to those :)

![image](https://user-images.githubusercontent.com/1908896/215615282-4ec1d001-748b-4ca7-8493-6dded5c55a52.png)

**Comment by flxzt** [comment]
The icon said flap, I thought it was the right one, also the sidebar icons don't indicate overlap. But don't have a strong opinion about changing it. Regarding the new-tab icon, I knew some app's use the other "plus" icon, but I thought it could confused as an action that modifies the canvas (like adding a page or something) because in the "fixed-size" layout mode there are buttons that do that also in the headerbar:

![Bildschirmfoto vom 2023-02-03 14-38-18](https://user-images.githubusercontent.com/19841886/216618232-09271241-6c14-47d9-9c56-66616da6e2cd.png)

I guess I keep picking the wrong icons out of the icon library, is there some sort of more curated list of suggestions for common actions for gnome apps somewhere or is this implicit convention in the ecosystem?

**Comment by PhilDevProg** [comment]
There's Adwaita Demo which shows many libadwaita widgets with their correct icons.

**Comment by flxzt** [comment]
the page controls are not in the headerbar anymore, so it is now possible to switch to the other "new-tab" icon
