### ISSUE TITLE
Can not change stylus shortcuts

### ISSUE THREAD

**Issue by Jan733-bit** [flxzt/rnote#536]
**Describe the bug**
The shortcuts for the stylus pen do not change when set up. For example I changed the primary button of my pen to the eraser_config, but when I press this button rnote changes into brush. Besides that after some work the setting changed by itself so now I always activate the typewriter by pressing my primary button, although I did not change anything.

**To Reproduce**
1. Go to 'Settings -> Shortcuts'
2. Click on 'Stylus primary button action -> anything but the default'.
3. Press the primary button, in different modes.
4. Repeat the change of the shortcut, if it works as intended. In my experience at least the second change does not work properly.
5. See error

**Expected behavior**
I except the config to change to the selected mode when pressing the primary button.

** Console Output **
no output

**Desktop (please complete the following information):**
 - OS: Linux Mint 21 Cinnamon
 -  Cinnamon: 5.4.12
 - Version: v0.5.14
 - Installation source Flatpak

**Comment by PJansky** [comment]
I've also had problems with the button shortcuts, but i don't think the problem lies with rnote. Wacom pens have an "eraser", a "primary" and "secondary" button. For instance on my PN579X the bottom button is defined as the eraser button  (I would have expected it to be the primary button) and the upper button on the same rocker is the primary button (I would have expected it to be the secondary button). It doesn't have a secondary button. I find this very confusing but this is the way it is. Can you confirm this isn't the problem you're having?

**Comment by Jan733-bit** [comment]
Hey, your answer makes sense, since my laptop sees my Active Pen by Lenovo as an generic Wacom pen. The reason I suspect rnote is because it worked in previous versions as intended and this "bug" did not appear.

**Comment by flxzt** [comment]
Try the following:  
- Hover over the canvas, and press and hold the button that doesn't work
- Switch to the desired tool while keeping the button pressed
- When releasing it, it should switch back to the previous tool.
- The tool should now be remembered

Unfortunately it is not possible to detect if this eraser mode is mapped to a button or the back side of the stylus (some have that). So the mapping is inconsistent. The only thing that could be done would be to add a help popup / add this explanation to the "Pitfalls" section in the README, because this comes up frequently.

**Comment by Jan733-bit** [comment]
Thanks, this worked.

**Comment by kgetech** [comment]
I am curious if we could consider another approach. For example, many non-wacom tablets and pens (such as the XP Pen line of products) allow you to bind a specific keyboard action (single button or combination press) to a stylus key. Perhaps allowing for more specific keyboard bindings could attempt to solve this problem?
