### ISSUE TITLE
update MacOS app bundle icon

### ISSUE THREAD

**Issue by flxzt** [flxzt/rnote#562]
The MacOS app bundle uses the outdated app icon.

@dehesselle could you update it ? I was not sure if this is automated in the workflow or done by hand.

**Comment by flxzt** [comment]
I meant that the app icon got updated since you created them for the bundle (slightly brighter colors, and some other tweaks). Otherwise the cropping is fine by me, if that is the intended look for MacOS

**Comment by dehesselle** [comment]
I will redo the icon this weekend.

**Comment by dehesselle** [comment]
Since I am not 100% satisfied with the look of the cropped icon, I've decided to use the native one and generate the macOS version during build. That also means that future changes to the icon will automatically be present in the macOS app as well.

New version of the macOS app (based on v0.5.18) with the updated icon will be released within approx. 60 minutes.

**Comment by dehesselle** [comment]
Done.

**Comment by flxzt** [comment]
thanks :)
