### ISSUE TITLE
Improved Zooming Functionality: Follow the Pointer

### ISSUE THREAD

**Issue by sadid** [flxzt/rnote#580]
First of all, thank you for this great app!

Currently, when using Ctrl+scroll to zoom in or out, the zooming is centered on the current center of the page. However, it would be more intuitive to have continuous zooming that follows the pointer, as is conventionally used in UI/UX design. This way, when the mouse pointer is moved, the Ctrl+scroll function will follow the pointer, making it easier to navigate without the need to zoom and pan repeatedly.

I have searched for this issue and have only found #539, but I believe it is not closely related to the problem I am describing.

**Comment by mizhozan** [comment]
First of all thanks for this great app and it seems the new zoom tool mentioned in the change log address this.

However, I tested the new zoom tool, but it doesn't work like other tools I'm familiar with. In programs like Inkscape, when you press Ctrl and scroll, the zoom follows the mouse pointer. However, in the new zoom tool, it behaves strangely and doesn't match the expected behavior described in this issue. In Rnote, there are now two zoom tools, but neither of them does what is intended. 

I couldn't understand how the new zoom tool is supposed to work—it shows two points, and the zoom depends on the distance between them, which is confusing to me. It would be helpful if the zoom tool followed the mouse pointer, like in other programs.
