### ISSUE TITLE
Buttons to copy to/paste from system clipboard 

### ISSUE THREAD

**Issue by LeSnake04** [flxzt/rnote#627]
**Please submit only one feature request in one issue!**

Please add buttons to interact with the system clipboard

**Is your feature request related to a problem? Please describe.**
Currently its impossible to interact with  the system clipboard in tablet mode unless you got an OSK with an CTRL key

**Describe the solution you'd like**
I propose buttons to copy /paste with the system clipboard
Paste: In the top bar, next to save
Copy: Selection menu, under the dublicate button

**Describe alternatives you've considered**

**Additional context**
This would also make it more obvious you can copy drawings between documents via the system clipboard

**Comment by flxzt** [comment]
Check the app menu, there are already "Copy, Cut and Paste" Actions availabe!

**Comment by LeSnake04** [comment]
Found it. But Its not really accesible so I am sure 99% wont notice it like me. 

Maybe it makes sense to make it more visible

**Comment by p-fruck** [comment]
I agree on this. I am using rnote with a convertible in tablet mode and I'd be glad to have a button that is more accessible to me. Currently, inserting screenshots into rnote is not a nice workflow since either I have to turn my keyboard around just to press ctrl + v or I have to dig down multiple submenus to paste the screenshot
