### ISSUE TITLE
Feature request: inverted pen color for export on documents with black background

### ISSUE THREAD

**Issue by flxzt** [flxzt/rnote#635]
### Discussed in https://github.com/flxzt/rnote/discussions/498

<div type='discussions-op-text'>

<sup>Originally posted by **liakhovitch** February  7, 2023</sup>
When exporting a file that has a dark background, it would be nice to have an "invert pen color" option along with the "remove background" option. This helps avoid the following scenario:
- I work on a homework assignment with a black background and white pen in order to save my eyes.
- When I export as a PDF so I can submit, I check "remove background".
- The exported file is now an all-white page

I don't know how OneNote does this, but there are a few variations on how this could work:
- Just swap any color exactly matching "black" and "white" on the default color palette (probably good enough for most cases)
- Invert the value of any color below a certain saturation

This would cover pretty much all of _my_ use cases, but it would also be nice to have the option to do this when switching backgrounds. Having an option to automatically invert both the background color and pen colors when switching between light/dark mode would also be helpful.

</div>

**Comment by Kneemund** [comment]
Inverting the colors should be fairly straight forward, it's mostly a matter of choosing a fitting color space. I've already made an imagemagick script for this, so I'll probably try to implement this soon-ish.

**Comment by Kneemund** [comment]
This still needs a lot of discussion, e.g.

- Should this be an export option? Should it be a document action, similar to clearing the document? Both?
- What should happen to the background? Should it stay as-is, or should it be inverted too?
    - The latter has the disadvantage that very dark gray backgrounds would be turned into very light gray backgrounds, which aren't suitable for printing. So it might be a better idea to leave that to the user.
 
> Having an option to automatically invert both the background color and pen colors when switching between light/dark mode would also be helpful.

I'm not sure if this is a good idea considering that this is not a simple visual change, but actually modifies all strokes (and potentially the background). Also, it could end up looking quite weird given that you can fully customize the background colors.

(Adding @liakhovitch to this issue since they are the one who originally created this.)
