### ISSUE TITLE
Hide drawing cursor

### ISSUE THREAD

**Issue by CR0CKER** [flxzt/rnote#649]
When using RNote with a pen on a touchscreen tablet, the drawing cursor can be quite distracting. I would love an option to hide it completely.

**Is your feature request related to a problem? Please describe.**  
Since I am writing on the touchscreen, the additional indicator that shows where the cursor is is not needed and distracting.

**Describe the solution you'd like**  
There should be an option to hide the drawing cursor.

**Describe alternatives you've considered**  
Switcxhing to Xournal+, but it's not as nice and has other issues.

**Comment by flxzt** [comment]
I wonder how this should be implemented. Either by adding another cursor that simply is invisible (but only to the drawing-cursor picker!), or by a "Hide drawing-cursor" toggle as a separate setting

**Comment by PhilDevProg** [comment]
I think a toggle would be the best way (or two toggles: one for when drawing and one for when not drawing) because putting an invisible cursor as an icon into the picker would be a little bit confusing in my opinion (and I don't even know how an invisible cursor could have an icon in the cursor picker since it's invisible...)
