### ISSUE TITLE
Linux: Add a binary release

### ISSUE THREAD

**Issue by Sigmw** [flxzt/rnote#657]
I'm on a Linux operating system free of flatpaks, I believe that most people who use it also don't always choose to use this tool, moreover, in the most raw way possible, a binary release for Linux would be excellent, containing instructions for libraries that should be installed in the operating system, rather than forcing the end user to install an entire package manager that they don't like.

**Comment by Intranox** [comment]
I would like a binary version as well, the problem I think lies on the fact that you can have problems with dependencies in some systems like on debian, rnote in fact uses gtk4 which is not not present in the bullseye repositories of Debian for example but only experimentally. 
An idea I think would be interesting would be to create an Appimage version so that there are no problems

**Comment by Sigmw** [comment]
An appimage would be perfect too, a small sandbox package with the libraries inside, which mounts the software only when it runs.

**Comment by flxzt** [comment]
I don't think a direct binary release can/will/should happen. I understand where you are coming from, but the application needs integration into the system and has external dependencies so there should always be some sort of package manager somewhere that does that.

If you want to install the application without a package manager, you can always build from source yourself. Here are [instructions, including listing external dependencies](https://github.com/flxzt/rnote/blob/main/BUILDING.md).

About appimages: there is some general discussion about it in #174. But I am sceptical, so upstream will probably only directly support flatpak's as package format on linux for the foreseeable future

I'll close this as "duplicate" of #174.
