### ISSUE TITLE
Windows 11 - Snap window not supported

### ISSUE THREAD

**Issue by Mitia99** [flxzt/rnote#796]
**Describe the bug**  
Windows 11 - Snap window not supported

**To Reproduce**  
Perform a mouseover action on the maximize window in title bar

**Expected behavior**  
![image](https://github.com/flxzt/rnote/assets/56766778/0a99305f-8af5-4108-8281-91d2eafa956c)

**Desktop (please complete the following information):**  
 - OS: Windows 11 22H2 
 - App Version: Rnote v0.8.2
 - Installation Source: Github repo

**Additional context**  
Maybe it's not a bug but not yet supported

**Comment by Doublonmousse** [comment]
This is a gtk4 limitation (see the related issue here on the gtk4 gitlab: https://gitlab.gnome.org/GNOME/gtk/-/issues/5327)

Rnote uses the gtk4 toolkit to build the application/interface and to be able to run it on multiple platforms. 
So every application using gtk4 will have this issue on windows and this can only be fixed by the gtk4 team.

**Comment by Mitia99** [comment]
> This is a gtk4 limitation (see the related issue here on the gtk4 gitlab: https://gitlab.gnome.org/GNOME/gtk/-/issues/5327)
> 
I see. Thanks for the info
