### ISSUE TITLE
[BUG]  Hamburger menu icon color not affected by theme

### ISSUE THREAD

**Issue by A-Walrus** [flxzt/rnote#995]
**Describe the bug**  
When in dark theme, the hamburger icon stays doesn't change color properly.

**To Reproduce**  
1. Set dark theme either through Gnome, or through rnote itself

**Expected behavior**  
Icon is white.

**Screenshots**  
![image](https://github.com/flxzt/rnote/assets/58790821/ea25a325-7a9d-4571-8755-b085e2fa67f7)

*light theme for reference*
![image](https://github.com/flxzt/rnote/assets/58790821/d169a4d7-fc77-4fcf-9d30-8f3f48697194)

**Desktop (please complete the following information):**  
 - OS: EndeavorOS
 - App Version: 0.9.4
 - Installation Source: Archlinux community repo
 - Desktop Environment: Gnome 45.3
 - Display Server: Wayland

**Comment by MooWaza** [comment]
I thought this could be an issue with how the icon is imported or referenced, since it's a standard icon that's replaced properly in every other app with the equivalent from the applied icon theme (in flatpaks and regular packages), but in Rnote doesn't show correctly with anything but adwaita. I may be missing something though.
